package common

/**
 * Created by 林 on 14-6-16.
 */
object JedisCacheKeys {
  //用户名缓存
  val USER_USERNAME_CACHE_KEY = "WXPAGE_USER_USERNAME_CACHE"
  //设置缓存
  val SETTING_VALUE_CACHE_KEY = "SETTING_VALUE_CACHE"
  /**
   * 手机号验证码存储
   */
  val PHONE_CODE_CACHE="PHONE_CODE_CACHE"

  val WEIXIN_TOKEN="WEIXIN_TOKEN"

  val WEIXIN_JS_TOKEN="WEIXIN_JS_TOKEN"

  val SETTING_MESSAGE_KEY="SETTING_MESSAGE_KEY"

  val TABLE_CACHE_KEY="TABLE_MESSAGE_KEY"

  val CLASSIFY_TABLE_CACHE_KEY="CLASSIFY_TABLE_MESSAGE_KEY"

  val SIZE_TABLE_CACHE_KEY="SIZE_TABLE_MESSAGE_KEY"

  val COLOUR_TABLE_CACHE_KEY="COLOUR_TABLE_MESSAGE_KEY"

  val BRAND_TABLE_CACHE_KEY="BRAND_TABLE_MESSAGE_KEY"

  val TAG_TABLE_CACHE_KEY="TAG_TABLE_MESSAGE_KEY"

  val WEIXIN_ID_CACHE_KEY="WEIXIN_ID_CACHE_KEY"

  val Product_PUBLIC_KEY="Product_PUBLIC_KEY"

  val TAG_PUBLIC_KEY="TAG_PUBLIC_KEY"

  val TAG_ARTICLE_PUBLIC_KEY="TAG_ARTICLE_PUBLIC_KEY"

  val INIT_CACHE_KEY="INIT_MESSAGE_KEY"

  val BRAND_PUBLIC_KEY="BRAND_PUBLIC_KEY"

  val AREA_PUBLIC_KEY="AREA_PUBLIC_KEY"

  val CLASSIFY_PUBLIC_KEY="CLASSIFY_PUBLIC_KEY"


}
